### PR TITLE
Fix column indexes. Fixes #4 and partly #16 (create function checks need to be fixed as well)

### LINKED ISSUE #4: Enforce `unique` for keys

### PR DESCRIPTION
**Pull request by jnssnmrcs**
This creates correct index kv keys depending on the type of index. Currently the create function is failing for non-unique indexes because it currently checks all keys for null versionstamps, which should not be done for non-unique index keys. This change also requires exactly 1 or 0 index types per column, since it does not make sense to have more than one of the currently supported index types on a single property.

### CODE REVIEW

**Comment by jnssnmrcs** [comment]
Maybe a separate issue should be created for updating the create-function to not check null versionstamps for non-unique keys

File: test/find_many_test.ts [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+    kv = await Deno.openKv();
+    db = createDatabase(kv);
+  });
+
+  beforeEach(async () => {
+    await populateDatabase(db);
+  });
+
+  // Ignored because currently failing
+  it.ignore("should return all posts", async () => {
```
Comment (jnssnmrcs) [inline test/find_many_test.ts:134]: Ignoring beacuse it is currently failing because create function checks non-unique index

**Comment by jnssnmrcs** [comment]
I'm fixing the create function in a separate branch at the moment but waiting for this to get merged before I put up a PR for it

**Comment by jnssnmrcs** [comment]
I realized it was something else that made the tests fail, it's fixed now and they pass.

**Comment by skoshx** [comment]
Thank you for making the changes! And apologies for taking so long with merging, have been incredibly busy!
